[general]
framerate = 60
bars = 28
bar_width = 1
bar_spacing = 0
noise_reduction = 65

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 32
frame_delimiter = 10
channels = mono
