# quickshell-notifications
sound_enabled=true
sound_event=message-new-instant
critical_sound_event=bell-window-system
do_not_disturb=false
dnd_collect_history=true
toast_duration_ms=5000
show_on_lock_screen=true
max_history=50
