# Generated by matugen — do not edit
set -g __qs_prompt_accent "{{ colors.primary.default.hex }}"
set -g __qs_prompt_fg "{{ colors.on_surface.default.hex }}"
set -g __qs_prompt_muted "{{ colors.outline.default.hex }}"
set -g __qs_prompt_err "{{ colors.error.default.hex }}"
set -g __qs_prompt_path_bg "{{ colors.surface_container_high.default.hex }}"
set -g __qs_prompt_time_bg "{{ colors.surface_container.default.hex }}"
