exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = awww-daemon
exec-once = bash ~/.config/hypr/scripts/wallpaper-init.sh
exec-once = bash ~/.config/hypr/scripts/start-quickshell.sh
exec-once = hypridle
