env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = $primary
    col.inactive_border = $outline_variant
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    shadow {
        render_power = 3
        color = rgba(00000066)
    }
}

animations {
    enabled = true

    bezier = easeOut, 0.16, 1, 0.3, 1
    bezier = easeInOut, 0.4, 0, 0.2, 1

    animation = windows, 1, 5, easeOut, slide
    animation = windowsOut, 1, 4, easeInOut, slide
    animation = border, 1, 8, easeOut
    animation = fade, 1, 6, easeOut
    animation = workspaces, 1, 5, easeOut, slide
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

cursor {
    no_hardware_cursors = false
}
