general {
    lock_cmd = hyprctl dispatch global quickshell:lock-screen
    before_sleep_cmd = hyprctl dispatch global quickshell:lock-screen
    inhibit_sleep = 3
}

listener {
    timeout = 900
    on-timeout = lock
}
